name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: cub3 CI
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: ./script/install_dependencies.sh

    - name: Check norm
      run: make check/norm

    - name: Compile Unit Tests
      run: make test.out

    - name: Run Unit Tests
      run: make check

    - name: Check For Leaks
      run: make check/leaks
